package pl.jvng.cryptomarketserver.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "crypto")
@NoArgsConstructor
@Data
public class Crypto {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    private String id;

    private String name;
    private String dataSourceUrl;

    public Crypto(String name, String dataSourceUrl) {
        this.name = name;
        this.dataSourceUrl = dataSourceUrl;
    }
}
